apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  volumes:
  - name: temp
    emptyDir: {}
  initContainers:
  - name: init-mycmd
    image: alpine:latest
    volumeMounts:
    - name: temp
      mountPath: /data
    command: ['sh', '-c', 'wget -O /data/myfile.txt https://raw.githubusercontent.com/ssmilecl/devops-interview-tests/master/myfile.txt']
  containers:
  - name: myapp-container
    image: alpine:latest
    volumeMounts:
    - name: temp
      mountPath: /data
    command: ['sh', '-c', 'cat /data/myfile.txt']
